//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChuyennganh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BaiViet
    {
        [Display(Name = "Mã bài viết")]
        public int MaBV { get; set; }
        [Display(Name = "Đăng bởi")]
        public string TenTKDang { get; set; }
        [Display(Name = "Cập nhật bởi")]
        public string TenTKCapNhat { get; set; }
        [Display(Name = "Ngày đăng")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime NgayDang { get; set; }
        [Display(Name = "Ngày cập nhật")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime NgayCapNhat { get; set; }
        [Display(Name = "Ảnh bìa")]
        public string HinhDD { get; set; }
        [Display(Name = "Tiêu đề")]
        public string TenBV { get; set; }
        [Display(Name = "Nội dung")]
        public string NoiDung { get; set; }

        public virtual NhanVien NhanVien { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
    }
}
