//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChuyennganh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DongHo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DongHo()
        {
            this.CTDonHangs = new HashSet<CTDonHang>();
            this.CTPhieuNhaps = new HashSet<CTPhieuNhap>();
        }

        [Display(Name = "Mã đồng hồ")]
        public string MaDH { get; set; }
        [Display(Name = "Thương hiệu")]
        public int MaTH { get; set; }
        [Display(Name = "Nguồn gốc")]
        public string NguonGoc { get; set; }
        [Display(Name = "Kiểu máy")]
        public string KieuMay { get; set; }
        [Display(Name = "Kích cỡ")]
        public string KichCo { get; set; }
        [Display(Name = "Độ dày")]
        public string DoDay { get; set; }
        [Display(Name = "Chất liệu vỏ")]
        public string ChatLieuVo { get; set; }
        [Display(Name = "Chất liệu dây")]
        public string ChatLieuDay { get; set; }
        [Display(Name = "Chất liệu kính")]
        public string ChatLieuKinh { get; set; }
        [Display(Name = "Độ chịu nước")]
        public string DoChiuNuoc { get; set; }
        [Display(Name = "Chức năng khác")]
        public string ChucNangKhac { get; set; }
        [Display(Name = "Giới tính")]
        public bool GioiTinh { get; set; }
        [Display(Name = "Hình đại diện")]
        public string HinhDD { get; set; }
        [Display(Name = "Số lượng")]
        public int SoLuong { get; set; }
        [Display(Name = "Mô tả chi tiết")]
        public string MoTaCT { get; set; }
        [Display(Name = "Giá bán")]
        public decimal GiaBan { get; set; }
        [Display(Name = "Giảm giá")]
        public Nullable<int> GiamGia { get; set; }
        [Display(Name = "Bảo hành")]
        public string BaoHanh { get; set; }
        [Display(Name = "Đăng bởi")]
        public string TenTKDang { get; set; }
        [Display(Name = "Cập nhật bởi")]
        public string TenTKCapNhat { get; set; }
        [Display(Name = "Ngày đăng")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime NgayDang { get; set; }
        [Display(Name = "Ngày cập nhật")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime NgayCapNhat { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDonHang> CTDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPhieuNhap> CTPhieuNhaps { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
        public virtual ThuongHieu ThuongHieu { get; set; }
    }
}
