//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChuyennganh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PhieuNhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuNhap()
        {
            this.CTPhieuNhaps = new HashSet<CTPhieuNhap>();
        }

        [Display(Name = "Số phiếu nhập")]
        public int SoPN { get; set; }
        [Display(Name = "Nhà cung cấp")]
        public int MaNCC { get; set; }
        [Display(Name = "Lập bởi")]
        public string TenTKLap { get; set; }
        [Display(Name = "Cập nhật bởi")]
        public string TenTKCapNhat { get; set; }
        [Display(Name = "Ngày nhập")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime NgayNhap { get; set; }
        [Display(Name = "Ngày cập nhật")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime NgayCapNhat { get; set; }
        [Display(Name = "Tổng số nhập")]
        public int TongSoNhap { get; set; }
        [Display(Name = "Thanh toán")]
        public decimal ThanhToan { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPhieuNhap> CTPhieuNhaps { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
    }
}
